import socket                                            #Allows the script to perform socket related actions
from concurrent.futures import ThreadPoolExecutor        #Allow the script to use workers / Threads to do multiple things at the same time

COMMON_PORTS = {                  #Dictionary of basic / cautionary ports and what they are for
    21: 'FTP',
    22:   'SSH',
    23:   'Telnet',
    25:   'SMTP',
    53:   'DNS',
    80:   'HTTP',
    110:  'POP3',
    135:  'MS-RPC',
    139:  'NetBIOS-SSN',
    143:  'IMAP',
    443:  'HTTPS',
    445:  'SMB',
    554:  'RTSP',
    993:  'IMAPS',
    995:  'POP3S',
    1900: 'SSDP/UPnP',
    3306: 'MySQL',
    3389: 'RDP',
    5000: 'UPnP/HTTP-Alt',
    5357: 'WSDAPI',
    8080: 'HTTP-Alt',
    8443: 'HTTPS-Alt'
}

def checkPort(ip: str, port: int, timeout: float = 0.5) -> str:
    """
    Checks the status of specific ports on a given IPv4 Address.

    Args:
        ip: A String representing an individual IPv4 Address that we want to check the ports of
        port: A Integer representing the port number that we want to check on our given IPv4 Address
        timeout: A Float representing the amount of time (in seconds) that the check waits before moving on

    Returns:
        String. This function returns a String representing the function of the port if it is open.
    """

    sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)    #Creates a new socket object that used IPv4 and TCP
    sock.settimeout(timeout)                                    #Sets the timeout for the socket

    try:
        result = sock.connect_ex((ip, port))            #Attempts a connection between the socket and the specific port on the IPv4 Address given
        if result == 0:                                 #Checks if it was successfull
            return COMMON_PORTS.get(port)               #If it was, we return the function of the port (eg. port 21 would return 'FTP')
    
    except OSError:        #If we get an OSError for any reason
        return 'N/A'       #We return N/A and move on
    
    finally:
        sock.close()       #Once we check the port of the specific IPv4 Address, we close the socket

def PScan(ip: str, ports: dict = COMMON_PORTS, timeout: float = 0.5, max_workers: int = 100) -> tuple:
    """
    Handles checking all of the common ports on a given IPv4 Address

    Args:
        ip: A String representing a given IPv4 Address to check the ports of
        ports: A Dictionary that represents the ports we are going to check on the IPv4 Address (default: COMMON_PORTS)
        timeout: A Float that represents the amount of time the workers are going to wait before moving on.
        max_workers: A Integer that represents the maximum number of workers we want the script to be able to use.

    Returns:
        Tuple. This function returns a Tuple that represents all the open ports found on the given IPv4 Address.
    """
    open_ports = []                #A list that is going to contain the open ports found

    with ThreadPoolExecutor(max_workers=min(len(ports), max_workers)) as executor:            #Opens up the ThreadPoolExecutor and sets the amount of workers available
        futures = {executor.submit(checkPort, ip, port, timeout): port for port in ports}     #Submits the checkPort function to the workers

        for future in futures:                    #Loops through each of the futures generated by the workers
            port = futures[future]                #Gets the port that they worked on
            if future.result():                   #Checks if the future returned anything
                open_ports.append(port)           #If it did, we append the port to the list of open ports

        if not open_ports:           #If no ports were open
            return "N/A"             #We return "N/A"
        
        open_ports.sort()            #If we do get some open ports, we sort them
        return ", ".join(str(p) for p in open_ports)         #Then we return a formatted version of the open port list
